### ISSUE TITLE
Cannot expand build on FAT32 formatted external HDD, Permission denied error #13

### ISSUE THREAD

**Issue by heunland** [Storj/dataserv-client#81] opened 2015-08-29 21:16 UTC
I get a permission denied error when trying to expand my already existing build to a bigger height. I am using an external HDD ADATA HD710 of 2 TB size, formatted with FAT32. The original build stopped building before getting to the expected max_size. After the server downtime last night I attempted to reinitiate building to expand to the bigger height with the following command:

I:\storj_beta_B\dataserv_client_203\dataserv-client>dataserv-client --url=http:/
/status.driveshare.org:5000 --max_size=1893000000000 --store_path I:\storj_beta_
B\data2 build --set_height_interval 2
Traceback (most recent call last):
 File "dataserv-client", line 10, in <module>
 File "E:\dataserv-client\dataserv_client\cli.py", line 153, in main
 File "E:\dataserv-client\dataserv_client\api.py", line 174, in build
 File "E:\dataserv-client\dataserv_client\builder.py", line 110, in build
 File "E:\dataserv-client\dataserv_client\builder.py", line 57, in generate_sha
rd
 File "C:\Python34\lib\site-packages\RandomIO\RandomIO.py", line 210, in genfil
e
PermissionError: [Errno 13] Permission denied: 'I:\\storj_beta_B\\data2\\4c35799217a590268073a9a524b52c351eeae2e1827f28f87235b212f8b62e3c'

It appears to have to do with the fact that my external drive is FAT32 formatted. It gives me a permission denied error when I try to expand a build I had previously started that for some reason never finished but stopped at height 11022 even though I was trying to build heigher. On the other hand, I am able to poll the existing build without problem. Rebooting the PC had no effect on the problem. I will report back if I manage to figure out how to fix it or rebuild from the beginning.

**Comment by littleskunk** [comment] 2015-08-30 18:30
Bug confirmed. I used a RAM Drive and build with 0 byte files. On FAT16 and FAT32 i get permission denied exception at height 10922. Folder structure and names change nothing.

With NTFS i was able to over height 1 000 000. Than my RAM Drive was full with 0 bytes files.

**Comment by ubronan** [comment] 2015-08-30 21:06
Bug confirmed with external usb2 drive fat32 formatted, exact same problem as described above.
It looks like its building at first but all 0 bytes files stopped at 10767 restarted build got permission denied error.
There seems to be no real writes taking place.

**Comment by rupertbg** [comment] 2015-09-01 04:01
Seems to a a similar issue on my system 6TB RAID configuration formatted as NTFS.

D:\dataserv-client>dataserv-client --store_path d:\dataserv-store --max_size 644
2450944000 --url http://status.driveshare.org:5000 build
Traceback (most recent call last):
  File "dataserv-client", line 10, in <module>
  File "E:\dataserv-client\dataserv_client\cli.py", line 153, in main
  File "E:\dataserv-client\dataserv_client\api.py", line 174, in build
  File "E:\dataserv-client\dataserv_client\builder.py", line 110, in build
  File "E:\dataserv-client\dataserv_client\builder.py", line 57, in generate_sha
rd
  File "C:\Python34\lib\site-packages\RandomIO\RandomIO.py", line 211, in genfil
e
  File "C:\Python34\lib\site-packages\RandomIO\RandomIO.py", line 187, in dump
PermissionError: [Errno 13] Permission denied

Weird thing is i don't have an E: drive on this machine, only C: and D:

**Comment by unsystemizer** [comment] 2015-09-01 04:07
@rupertbg it's telling you you don't have permission to write to D:\dataserv-store.
Make sure your filesystem is NTFS and give the user proper permissions.
E:\ is probably remnants of your old 1.3.0, or you messed the system up by improperly removing and inserting USB drives in your PC. Reboot and recheck.

**Comment by littleskunk** [comment] 2015-09-01 15:11
Subfolders would be a solution. I see 3 different possibilities to implement that.

1.) First 4 char for the folder and everything else for the files. That would create 65536 folder and ~78 petabyte could be stored. First 2 char would work as well with 256 folders and ~312 terabyte.
2.) Every 4 char one subfolder and only the last 4 char for the file. Every posible files could be safed. 16^64 files.
3.) Every 10000 height one folder. max 11 petabyte.

1 and 2 would also work in the final release. I think the final release will work without height. 3 would only work in the test group.

Migration of the existing files is possible.
Which solotion do you like? Test with my FAT32 RAM Drive will only need ~30 minutes.

**Comment by heunland** [comment] 2015-09-01 15:18
I prefer option 2 but if the devs think there is some reason to implement another solution of course the most practical solution that is also compatible to be implemented in the final release would be best.

**Comment by unsystemizer** [comment] 2015-09-01 19:06
@littleskunk 78 PB on FAT32?

**Comment by littleskunk** [comment] 2015-09-01 19:19
Theoretically yes. Based on the main problem in this bug ofc. 65 536 folder with 10 000 files and 128 MB. Did i calculated something wrong?

**Comment by unsystemizer** [comment] 2015-09-01 19:23
> The boot sector uses a 32-bit field for the sector count, limiting the FAT32 volume size to 2 TB for a sector size of 512 bytes and 16 TB for a sector size of 4,096 bytes.

https://en.wikipedia.org/wiki/File_Allocation_Table#FAT32

IMO FAT32 shouldn't be supported, it's a legacy filesystem unsuitable for mining.

**Comment by ubronan** [comment] 2015-09-01 19:36
Well your right its indeed having problems when total files goes over a maximum
There for was recommended to use sub directories to prevent problems
However if i remember it well, some older usb2 drives can not be formatted with ntfs they can become totally useless. I would strongly advise people to check if the drive can be formatted with NTFS.

**Comment by littleskunk** [comment] 2015-09-01 19:50
I dont care about political issues about FAT32. heunland would like to use a 2 TB FAT32 HDD and i dont see a reason why we should not support this 2TB Drive. Other user asked for folders on there NTFS Drive. 
I found the reason for the bug and a solution. Now devs have to decide.

**Comment by littleskunk** [comment] 2015-09-03 20:37
Calculated Option 1 and 2 wrong. 65 536 folder with a 10 000 limit is not possible. 3 char with 4096 folder would be possible. Option 1 with 3 char would be ~ 5 peta byte. I would prefer that option. Easy to implement and 5 peta byte should be enough and it will work in the final relase as well.

**Comment by F483** [comment] 2015-09-04 15:51
After some research it seems @littleskunk is correct. The maximum amount of files per folder in fat32 depends on the size of the clusters, but a limiting it to 2^13  seems to be a save option.

Since fat32 is sadly far to prevalent to ignore we have to address this by splitting the files into folders. But I also don't wand to break the rebuild for previous clients unless its need so I propose the following solution.

Try to detect if the path is on a fat32 partion or add and argument to switch into folder grouping mode `--fat32`.

As for how to structure the folder tree. We have to consequently limit the tree to 2^13 folders per folder or we have solved nothing. Because splitting every 13 bytes is not practical for a hex encode file name. We have to go farther down to splitting every 12 bytes, which is every 3 chars.

Example `C:\2b2\4f1\a8e\ff1\d35\9d7\70f\1a1\94d\6b3\aab\867\b32\4cf\558\dcc\c4b\121\88f\1bf\6a9\4`

Request for comment @super3 @littleskunk

**Comment by littleskunk** [comment] 2015-09-04 17:30
I like the --fat32 switch and i did not find a manual to autodetect fat32.

I think we should use the full file name. That way the user can copy all files from a fat32 drive to a ntfs drive without loosing files.

User starts building without fat32 switch. After some time he will get a exception. User starts building again with fat32 switch. Time to move the old files into new folder structure.

**Comment by F483** [comment] 2015-09-04 18:04
Having the final file contain the full file name or not doesn’t matter to much for copying files. 
I will add it so it does, resulting in the following example.

`C:\2b2\4f1\a8e\ff1\d35\9d7\70f\1a1\94d\6b3\aab\867\b32\4cf\558\dcc\c4b\121\88f\1bf\6\2b24f1a8eff1d359d770f1a194d6b3aab867b324cf558dccc4b12188f1bf6a94`

**Comment by F483** [comment] 2015-09-04 20:54
Actually it seems you can detect the fs type pretty easily. https://github.com/Storj/dataserv-client/blob/develop/dataserv_client/util.py

I will make it use a folder tree on fat32 by default and add an option for it, so you can copy from a fat32 partition to a different one and still have it work.

Any suggestions for a short and clear name, where it is obvious what it does? For now I will use `--store_in_folder_tree`

**Comment by F483** [comment] 2015-09-06 18:10
I added the option `--use_folder_tree` in the develop branch that automatically set if the store_path is on a fat32 drive.

@littleskunk can you confirm it works?

**Comment by littleskunk** [comment] 2015-09-06 23:32
@F483
The last folder is not needed
C:\2b2\4f1\a8e\ff1\d35\9d7\70f\1a1\94d\6b3\aab\867\b32\4cf\558\dcc\c4b\121\88f\1bf\6a9\ would work as well.

I build without --use_folder_tree and after i switched it on. It starts with height 0 again. If possible we should give heunland the version as soon as possible. She needs some time to build the 10.000 files again.

Resuming from last height with folder tree works great. I was able to write ~100.000 files on a fat16 ram drive. Well done :)

**Comment by F483** [comment] 2015-09-07 11:15
Yeah the last folder is not needed, but it doesn't hurt as well. So we might as well keep it to have the complete sha256sum.

Yes the client is getting quite stable, I may make a build today and we release it tomorrow morning. That depends on what @super3 thinks.

**Comment by F483** [comment] 2015-09-07 11:15
Closing the issue as it seems resolved.

**Closed by F483** 2015-09-07 11:15 UTC
Labels: bug
